# -*- coding: utf-8 -*-
"""bgpelectric.ipynb

Automatically generated by Colaboratory.

"""

import requests
from bs4 import BeautifulSoup
from pprint import pprint
from lxml import etree
import os
from google.colab import files
import json,csv

#edit this part with your values
domain = ["domain1.com","domain2.com","domain3.com","domain4.com"]

# lets form url for this domains
dnsurl = []
ipurl = []

for i in domain:
  tempdnsurl = "https://www.robtex.com/dns-lookup/" + i
  dnsurl.append(tempdnsurl)
  #tempipurl = tempdnsurl + "#_ipinfo"
  #ipurl.append(tempipurl)
  #print ("dns-",tempdnsurl)
  #print ("ip-",tempipurl)

# now i have formed the urls for requests to be made
# next step is identify the way to pull individual information
# You will need to manupulate the useragent else bgp electric will block you
#firstline no need pulling of information

ipaddresslist = []
nameserver1list = []
nameserver2list = []
mailserver1list = []
mailserver2list = []


for i in dnsurl:
  # you have to edit the useragent so you wont be blocked
  user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.47 Safari/537.36'
  headers = {'User-Agent': user_agent}
  response = requests.get(i,headers=headers)
  writehtml = open ("response.html",'w',newline='')
  writehtml.write (response.text)
  
  #You have stored the file now your job is parsing
  htmlparser = etree.HTMLParser()
  tree = etree.parse('/content/response.html',htmlparser)
  
  #finding how to pull the individual information
  ipaddress = tree.xpath('/html/body/main/article/div/div[4]/div/div[2]/div[2]/div[2]/section[2]/div[3]/table/tbody/tr[8]/td/a/text()')
  #if you dont use the if else condition you will get index error , if there is no value returned add none is returned
  if ipaddress == []:
    ipaddresslist.append("nonefound -"+i)
  else:
    ipaddresslist = ipaddresslist + ipaddress
 
  nameserverbegend = tree.xpath('/html/body/main/article/div/div[4]/div/div[2]/div[2]/div[2]/section[2]/div[3]/table/tbody/tr[9]/td/ul/li[1]/a/text()')
  nameservermiddle = tree.xpath('/html/body/main/article/div/div[4]/div/div[2]/div[2]/div[2]/section[2]/div[3]/table/tbody/tr[9]/td/ul/li[1]/a/b/text()')
  nameserver1 = []
  #fordebug-print(i,"-",nameservermiddle)
  if nameservermiddle == []:
    nameserver1.append("nonefound -"+i)
    nameserver1list = nameserver1 + nameserver1list

  else:
    nameserver1.append(nameserverbegend[0]+nameservermiddle[0]+nameserverbegend[1])
    nameserver1list = nameserver1 + nameserver1list
 
  nameserver2 = []
  nameserverbegend2 = tree.xpath('/html/body/main/article/div/div[4]/div/div[2]/div[2]/div[2]/section[2]/div[3]/table/tbody/tr[9]/td/ul/li[2]/a/text()')
  nameservermiddle2 = tree.xpath('/html/body/main/article/div/div[4]/div/div[2]/div[2]/div[2]/section[2]/div[3]/table/tbody/tr[9]/td/ul/li[2]/a/b/text()')
  if nameservermiddle2 == []:
    nameserver2.append("nonefound -"+i)
    nameserver2list = nameserver2 + nameserver2list
  else:
    nameserver2.append(nameserverbegend2[0]+nameservermiddle2[0]+nameserverbegend2[1])
    nameserver2list = nameserver2 + nameserver2list
 
  mailserver1 = []
  mailserverbegend = tree.xpath('/html/body/main/article/div/div[4]/div/div[2]/div[2]/div[2]/section[2]/div[3]/table/tbody/tr[10]/td/ul/li[1]/a/text()')
  mailservermiddle = tree.xpath('/html/body/main/article/div/div[4]/div/div[2]/div[2]/div[2]/section[2]/div[3]/table/tbody/tr[10]/td/ul/li[1]/a/b/text()')
  if mailservermiddle == []:
    mailserver1.append("nonefound -"+i)
    mailserver1list = mailserver1list + mailserver1
  else:
    mailserver1.append(mailserverbegend[0]+mailservermiddle[0]+mailserverbegend[1])
    mailserver1list = mailserver1list + mailserver1

  mailserver2 = []
  mailserverbegend2 = tree.xpath('/html/body/main/article/div/div[4]/div/div[2]/div[2]/div[2]/section[2]/div[3]/table/tbody/tr[10]/td/ul/li[2]/a/text()')
  mailservermiddle2 = tree.xpath('/html/body/main/article/div/div[4]/div/div[2]/div[2]/div[2]/section[2]/div[3]/table/tbody/tr[10]/td/ul/li[2]/a/b/text()')
  if mailservermiddle2 == []:
    mailserver2.append("nonefound -"+i)
    mailserver2list = mailserver2list + mailserver2
  else:
    mailserver2.append(mailserverbegend2[0]+mailservermiddle2[0]+mailserverbegend2[1])
    mailserver2list = mailserver2list + mailserver2
  # Writing in a CSV



domaininfowrite = open('domaininfotoday2.csv','w',newline='')
writer = csv.writer(domaininfowrite,lineterminator='\n')
writer.writerow(['domain','ipaddress','nameserver1','nameserver2','mailserver1','mailserver2'])
for i in range(len(domain)): 
	writer.writerow([domain[i],ipaddresslist[i],nameserver1list[i],nameserver2list[i],mailserver1list[i],mailserver2list[i]])

#to download from google cloud
files.download('/content/domaininfotoday2.csv')

