# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TBhi_01bcpojMVAbh4A3MqajcwcP3gD7
"""

import requests
from bs4 import BeautifulSoup

html =  requests.get("https://nvd.nist.gov/vuln/detail/CVE-2019-13307")

bs = BeautifulSoup(html.text,'html.parser')

description = bs.findAll('p',attrs={'data-testid':'vuln-description'})

description[0].get_text()

vector = bs.findAll('span',attrs={'class':'tooltipCvss3NistMetrics'})

vector[0].get_text()

score = bs.findAll('a',attrs={'id':'p_lt_WebPartZone1_zoneCenter_pageplaceholder_p_lt_WebPartZone1_zoneCenter_VulnerabilityDetail_VulnFormView_Cvss3NistCalculatorAnchor'})

score[0].get_text()



